# Generated by Django 4.2.6 on 2023-10-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocNum', models.CharField(max_length=11)),
                ('Name', models.CharField(max_length=225, null=True)),
                ('Password', models.CharField(max_length=225, null=True)),
            ],
        ),
    ]
